spring:
  application:
    name: Blog Application
  data:
    mongodb:
      # uri: mongodb+srv://odevg:asgd912jksn7paiud@devblog.iqrfcad.mongodb.net/Development?retryWrites=true&w=majority
      uri: mongodb://localhost:27017/KassiopeiaDevelopment
  mvc:
    static-path-pattern: /public/**
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

server:
  port: 7000
  tomcat:
    relaxed-query-chars: ['{', '}', '[', ']', '|', '\', '^', '~', '`']
    relaxed-path-chars: ['{', '}', '[', ']', '|', '\', '^', '~', '`']

aws:
  s3:
    bucket:

kassiopeia:
  jwt:
    key: 3Js7I9toygrSJydphpxWzWxMhVMOz8kFPjm
    issuer: Blog Kassiopeia.dev
    audience: ${AUDIENCE:http://127.0.0.1}
